"""Explicit user corrections applied before evidence compilation and rendering."""
from __future__ import annotations

import copy
from datetime import datetime, timezone
from typing import Any, Mapping


def evidence_ids(value: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(value, Mapping):
        for key, item in value.items():
            if key in {"memory_id", "source_record_id", "record_id", "claim_id", "semantic_memory_id", "message_id", "source_message_id"}:
                if isinstance(item, str):
                    found.add(item)
            elif key == "session_id" and isinstance(item, str) and item.startswith("correction-fb_"):
                # Indexed source IDs are generated by the writer. The correction
                # session survives retrieval and links those sources to feedback.
                found.add(item.removeprefix("correction-"))
            elif key in {"source_record_ids", "semantic_record_ids", "support", "counterevidence"}:
                if isinstance(item, list):
                    found.update(part for part in item if isinstance(part, str))
            found.update(evidence_ids(item))
    elif isinstance(value, list):
        for item in value:
            found.update(evidence_ids(item))
    return found


def apply_feedback(evidence: Mapping[str, Any], effects: Mapping[str, Any]) -> dict[str, Any]:
    result = copy.deepcopy(dict(evidence))
    windows = []
    corrections: dict[str, Any] = {}
    suppressed: list[str] = []
    for window in result.get("evidence_windows", []):
        matches = {key: effects[key] for key in evidence_ids(window) if key in effects}
        if not matches:
            windows.append(window)
            continue
        # Remove the entire affected window, including derived/neighbor context.
        # Immutable originals stay in storage and audit history.
        suppressed.extend(matches)
        direct = [effect for effect in matches.values() if effect["action"] != "correction_alias"]
        # A direct source override takes precedence over an indexed correction's
        # canonical redirect (for example, explicitly ignoring that indexed row).
        governing = direct or list(matches.values())
        for effect in governing:
            replacements = effect.get("corrections", [effect])
            for replacement in replacements:
                if replacement["action"] == "correct":
                    corrections[replacement["feedback_id"]] = replacement
    for feedback_id, effect in corrections.items():
        windows.append({
            "source_record_id": feedback_id,
            "text": effect["replacement"],
            "actor_role": "user",
            "authority": "explicit_user_correction",
            "timestamp": datetime.fromtimestamp(effect["created_at"], timezone.utc).isoformat(),
            "session_id": f"correction-{feedback_id}",
            "memory_contexts": [], "attachments": [], "source_group_context": [],
        })
    result["evidence_windows"] = windows
    if suppressed:
        # The compiler must receive only the filtered evidence, with no stale
        # flattened packet or cached answer-facing content from the retriever.
        result = {"evidence_windows": windows, "recall_plan": result.get("recall_plan", {}),
                  "feedback_applied": {"suppressed_ids": sorted(set(suppressed)),
                                       "correction_ids": list(corrections)}}
    return result
